UI/added basic css
TheGogy/cw-esp pull request #7
Opened 2024-02-08 20:25 UTC by sef007

added CSS to UI.

2024-02-08 23:51 UTC, box1273002 requested changes
Sorry for being mean. any chance you could fix these.

2024-02-08 23:51 UTC, box1273002 commented on .DS_Store
These are random temp files from mac. They are like the nine headed hydra they keep coming back. I accidentally and them a while ago. THEY WILL NOT GO can you please remove them. p.s there also one in the models folder.

2024-02-08 23:51 UTC, box1273002 commented on SubtitleWindow.py
> +        # load the style sheet
Can you please remove random commented out code.

2024-02-08 23:51 UTC, box1273002 commented on Users/ExampleUserCSS.css
I am pretty sure you deleted this by accident. can you put it back please.

2024-02-08 23:51 UTC, box1273002 commented on SettingsWindow.py
> +        # print("Stylesheet content:")
Can you please delete commented out code

2024-02-09 15:02 UTC, sef007 reviewed
changes should be implemented

2024-02-09 15:02 UTC, sef007 commented on .DS_Store
now in gitignore

2024-02-09 15:13 UTC, TheGogy commented on .gitignore
> +
```suggestion

```

2024-02-09 15:13 UTC, TheGogy commented on .gitignore
> +
Remove trailing newline

2024-02-09 15:18 UTC, TheGogy commented on SettingsWindow.py
> +        self.loadStylesheet("styles/css_file.qss")
```suggestion
        self.cssPath = Path(__file__) / "styles/css_file.qss"
        self.loadStylesheet(self.cssPath)
```

2024-02-09 15:19 UTC, TheGogy commented on SettingsWindow.py
> +        self.loadStylesheet("styles/css_file.qss")
Would be good to use relative paths so that the script can be run from any working directory

2024-02-09 15:19 UTC, TheGogy commented on SettingsWindow.py
> +from PyQt5.QtCore import QFile, QTextStream
```suggestion
```

2024-02-09 15:24 UTC, TheGogy commented on SettingsWindow.py
> +
```suggestion
```

2024-02-09 15:24 UTC, TheGogy commented on SettingsWindow.py
> +
Remove trailing newline

2024-02-09 15:24 UTC, TheGogy commented on styles/Picture1.png
Beautiful

2024-02-09 15:33 UTC, TheGogy commented
Overall looks good, a few minor changes but those should be sorted

2024-02-09 16:06 UTC, sef007 reviewed
implemented changes

2024-02-13 10:53 UTC, TheGogy commented on SettingsWindow.py
> +from PyQt5.QtCore import QFile, QTextStream
```suggestion
```

2024-02-13 10:53 UTC, TheGogy commented on SettingsWindow.py
>  from PyQt5.QtCore import  pyqtSignal, QObject,QRect,QEvent,Qt
```suggestion
from PyQt5.QtCore import  pyqtSignal, QObject, QRect, QEvent, Qt, QFile, QTextStream
```

2024-02-13 11:05 UTC, TheGogy reviewed
We needed to keep the ExampleUserCSS!
Also fixed a few imports

2024-02-13 11:06 UTC, TheGogy approved these changes

2024-02-13 11:13 UTC, merged